### ISSUE TITLE
Add dependencies

### ISSUE THREAD

**Issue by yswhynot** [HybridRobotics/NMPC-DCLF-DCBF#4]
Hi,

I find your work to be very interesting and I'd like to try run your code (ACC 2021 to be specific). However, it seems the optimization with the sdpsettings relies on `ipopt` solver. The documentation [here](https://yalmip.github.io/solver/ipopt/) says it's based on the [OPTI Toolbox](https://github.com/jonathancurrie/OPTI), which seems to only work on Windows. 

Sorry that I'm not a very experienced Matlab user. May I know am I following the correct path to set up the dependency? Is Windows really required?

**Comment by junzengx14** [comment]
Thank you for your interests, actually all my implementations are tested on ubuntu 18.04 system while not on windows. ipopt has mex file version, which can be found in the original archived repo [link](https://github.com/HybridRobotics/MPC-CBF/tree/master/packages). Unzip that file and add it into your matlab address and it would solve your bugs. 

Raise further questions or you cannot figure it out.

**Comment by yswhynot** [comment]
Thank you it works!

**Comment by junzengx14** [comment]
Let me just open it and I can upload dependencies for later users.

**Comment by junzengx14** [comment]
@yswhynot A new PR resolves this, thank you for pointing it out.
