### ISSUE TITLE
Bug shooting for Solver Infeasible (ACC2021)

### ISSUE THREAD

**Issue by Highlight123** [HybridRobotics/NMPC-DCLF-DCBF#8]
Dear Dr. Zeng
     Thanks for sharing this repo and your work in using NMPC, DCBF and DCLF for the safety and stability of non-linear dynamic systems. When I run testGamma.m and testHorizon.m in acc2021 with matlab2021a and Ipopt from https://ww2.mathworks.cn/matlabcentral/fileexchange/53040-ebertolazzi-mexipopt, I have the following problem. Thank you very much for your kind consideration and I am looking forward to your reply.
(1) testGamma.m
Run MPC-CBF with gamma 1.000000
solver time: 0.203114
solver time: 0.173155
solver time: 0.190210
solver time: 0.164076
solver time: 0.187111
solver time: 0.192042
solver time: 0.207878
The dimensions used for matrix multiplication are incorrect. Check to make sure that the number of columns in the first matrix matches the number of rows in the second matrix. To multiply by elements, use '.*'.
error: MPCCBF/sim (line 33)
                xk = self.system.A * xk + self.system.B * uk;
error: testGamma (line 50)
    controller_mpc_cbf_list{ind}.sim(time_total);
(2) testHorizon.m
Function or variable 'MPC_CBF' is not recognized.
error: testHorizon (line 57)
controller_mpc_cbf_3 = MPC_CBF(x0, system, params);

**Comment by junzengx14** [comment]
Hi, I appears to me an infeasible issue, are you running the code provided in this repository?

**Comment by Highlight123** [comment]
Dear Dr. Zeng
    thank your support! I have read your ACC and CDC paper carefully. Your work is outstanding and innovative! 
Bug shooting for Solver Infeasible is caused by the IPOPT version. The zipped IPOPT mex files seems to be oriented towards Mac rather than windows. May I ask you how to install Ipopt in windows and matlab2021a environment?

**Comment by junzengx14** [comment]
@hesuieins Do you have any experience of IPOPT in windows? Maybe we can add a zipped version of windows mex files if there are?

**Comment by hesuieins** [comment]
I have a zipped version for Windows. Should I upload it here or to the repo directly?

**Comment by junzengx14** [comment]
Could you make a PR for it?

**Comment by junzengx14** [comment]
@Highlight123 We merged a PR for supporting windows, please check it out.

**Comment by Highlight123** [comment]
Thank your help！This problem has been solved

**Comment by junzengx14** [comment]
@Highlight123 Please star and fork to support our work if possible, thanks!

**Comment by Highlight123** [comment]
Sure, I have star this work and follow Hybrid Robotics .
